# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: metatile.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='metatile.proto',
  package='tiles',
  serialized_pb=_b('\n\x0emetatile.proto\x12\x05tiles\"\x14\n\x04Tile\x12\x0c\n\x04tile\x18\x01 \x02(\x0c\"D\n\x08Metatile\x12\x0c\n\x04size\x18\x01 \x02(\x05\x12\x0e\n\x06\x66ormat\x18\x02 \x02(\t\x12\x1a\n\x05tiles\x18\x03 \x03(\x0b\x32\x0b.tiles.Tile')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_TILE = _descriptor.Descriptor(
  name='Tile',
  full_name='tiles.Tile',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tile', full_name='tiles.Tile.tile', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=45,
)


_METATILE = _descriptor.Descriptor(
  name='Metatile',
  full_name='tiles.Metatile',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='size', full_name='tiles.Metatile.size', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='format', full_name='tiles.Metatile.format', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tiles', full_name='tiles.Metatile.tiles', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=115,
)

_METATILE.fields_by_name['tiles'].message_type = _TILE
DESCRIPTOR.message_types_by_name['Tile'] = _TILE
DESCRIPTOR.message_types_by_name['Metatile'] = _METATILE

Tile = _reflection.GeneratedProtocolMessageType('Tile', (_message.Message,), dict(
  DESCRIPTOR = _TILE,
  __module__ = 'metatile_pb2'
  # @@protoc_insertion_point(class_scope:tiles.Tile)
  ))
_sym_db.RegisterMessage(Tile)

Metatile = _reflection.GeneratedProtocolMessageType('Metatile', (_message.Message,), dict(
  DESCRIPTOR = _METATILE,
  __module__ = 'metatile_pb2'
  # @@protoc_insertion_point(class_scope:tiles.Metatile)
  ))
_sym_db.RegisterMessage(Metatile)


# @@protoc_insertion_point(module_scope)
